// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnquoUrN7JWRiW1s5bcMp-g9QB-6HJ7lM',
    appId: '1:471463861930:web:9c3766bd23af4bb501fad3',
    messagingSenderId: '471463861930',
    projectId: 'mercado-superpao',
    authDomain: 'mercado-superpao.firebaseapp.com',
    storageBucket: 'mercado-superpao.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBESb6RMsES_0Wl_1Ep_BQjJpbssuB4t1I',
    appId: '1:471463861930:android:b3fa7d746e350ad501fad3',
    messagingSenderId: '471463861930',
    projectId: 'mercado-superpao',
    storageBucket: 'mercado-superpao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaY3g3A-Z9GvBwzm9XNc6aU9fI6Jejnys',
    appId: '1:471463861930:ios:103e93404cc0d5bb01fad3',
    messagingSenderId: '471463861930',
    projectId: 'mercado-superpao',
    storageBucket: 'mercado-superpao.appspot.com',
    iosBundleId: 'com.luvizotto.minimercado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaY3g3A-Z9GvBwzm9XNc6aU9fI6Jejnys',
    appId: '1:471463861930:ios:103e93404cc0d5bb01fad3',
    messagingSenderId: '471463861930',
    projectId: 'mercado-superpao',
    storageBucket: 'mercado-superpao.appspot.com',
    iosBundleId: 'com.luvizotto.minimercado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnquoUrN7JWRiW1s5bcMp-g9QB-6HJ7lM',
    appId: '1:471463861930:web:2fc62d1dd7bfe4b101fad3',
    messagingSenderId: '471463861930',
    projectId: 'mercado-superpao',
    authDomain: 'mercado-superpao.firebaseapp.com',
    storageBucket: 'mercado-superpao.appspot.com',
  );

}